# Create a pod that runs rabbitmq container inside

apiVersion: v1
kind: Pod
metadata:
  namespace: local-applications
  name: rabbitmq
  labels:
    app: rabbitmq

spec:
  containers:
    - name: rabbitmq
      image: rabbitmq
      ports:
        - containerPort: 8080